# Generated by Django 4.2.17 on 2024-12-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreachedCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("file", models.CharField(max_length=255)),
                ("password_hash", models.CharField(max_length=255)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
