# Generated by Django 4.2.18 on 2025-02-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "sha256",
                    models.CharField(
                        default="", editable=False, max_length=256, unique=True
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "size",
                    models.CharField(
                        default=0, help_text="Size of the file in mb", max_length=8
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BreachedCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string", models.CharField(max_length=512)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breached_credentials",
                        to="webui.scrapfile",
                    ),
                ),
            ],
        ),
    ]
