# Generated by Django 4.2.17 on 2024-12-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breachedcredential",
            name="password_hash",
        ),
        migrations.AddField(
            model_name="breachedcredential",
            name="hash",
            field=models.CharField(
                default="sha256value", editable=False, max_length=256
            ),
        ),
        migrations.AddField(
            model_name="breachedcredential",
            name="hash_type",
            field=models.CharField(default="sha256", max_length=32),
        ),
        migrations.AlterField(
            model_name="breachedcredential",
            name="file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="breachedcredential",
            name="source",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
