# Generated by Django 4.2.17 on 2024-12-06 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0003_alter_breachedcredential_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("hash", models.CharField(editable=False, max_length=256, unique=True)),
                ("hash_type", models.CharField(max_length=32)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="breachedcredential",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breached_credentials",
                to="webui.scrapfile",
            ),
        ),
    ]
