# Generated by Django 4.2.19 on 2025-03-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0003_scrapfile_is_active_alter_breachedcredential_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapfile",
            name="count",
            field=models.IntegerField(
                default=0, help_text="Number of associated BreachedCredentials"
            ),
        ),
    ]
