# Generated by Django 4.2.19 on 2025-03-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0004_scrapfile_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breachedcredential",
            name="string",
            field=models.CharField(max_length=1024),
        ),
    ]
