# Generated by Django 4.2.17 on 2024-12-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0005_alter_breachedcredential_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breachedcredential",
            name="file",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
