# Generated by Django 4.2.19 on 2025-03-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0005_alter_breachedcredential_string"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="breachedcredential",
            name="webui_breac_string_63808b_idx",
        ),
    ]
