# Generated by Django 4.2.20 on 2025-04-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0006_remove_breachedcredential_webui_breac_string_63808b_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breachedcredential",
            name="id",
            field=models.CharField(
                editable=False, max_length=32, primary_key=True, serialize=False
            ),
        ),
    ]
