# Generated by Django 4.2.17 on 2024-12-06 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0007_alter_breachedcredential_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breachedcredential",
            name="file",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breached_credentials",
                to="webui.scrapfile",
            ),
        ),
    ]
