# Generated by Django 4.2.17 on 2024-12-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webui", "0008_alter_breachedcredential_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="breachedcredential",
            name="website",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
